### ISSUE TITLE
Dataset used in the repo (sunrgbd_rgb_training.txt)

### ISSUE THREAD

**Issue by xavysp** [ankurhanda/tf-unet#2]
Hi,
 excuse me, I want to know what kind of info has the **sunrgbd_rgb_training.txt** file, could we access such a file?
https://github.com/ankurhanda/tf-unet/blob/73a15a14afc4a02d6ef4616def020235eaed2084/train_u-net.py#L53

**Comment by ankurhanda** [comment]
see here: https://github.com/ankurhanda/sunrgbd-meta-data
